"""Branded HTML email layouts for Softude Ops Console notifications."""

from __future__ import annotations

import os
from html import escape
from typing import Any


def brand_name() -> str:
    return (os.getenv("EMAIL_BRAND_NAME") or "Softude Ops Console").strip()


def product_name() -> str:
    return (os.getenv("EMAIL_PRODUCT_NAME") or "Softude AI").strip()


def brand_logo_url() -> str:
    default = "https://www.softude.com/wp-content/uploads/2024/11/logo.png"
    return (os.getenv("EMAIL_BRAND_LOGO_URL") or default).strip()


def dashboard_url(fallback: str = "") -> str:
    return (
        os.getenv("DASHBOARD_URL")
        or fallback
        or "https://ai-automation-agents-plum.vercel.app"
    ).strip().rstrip("/")


def render_branded_email(
    *,
    eyebrow: str,
    title: str,
    intro_html: str,
    rows: list[tuple[str, str]],
    cta_label: str | None = None,
    cta_url: str | None = None,
    badge: str | None = None,
    accent: str = "#14b8a6",
    badge_bg: str = "#ccfbf1",
    badge_text: str = "#0f766e",
    footer_note: str | None = None,
) -> str:
    """Return a full HTML email with Softude product styling.

    Includes subtle CSS animations where supported (Apple Mail, Gmail web).
    Outlook and older clients fall back to the same static layout.
    """
    brand = escape(brand_name())
    product = escape(product_name())
    logo = brand_logo_url()
    logo_html = ""
    if logo:
        logo_html = (
            f'<img class="softude-logo" src="{escape(logo, quote=True)}" alt="{brand}" '
            'width="140" height="32" '
            'style="display:block;border:0;margin-bottom:14px;max-width:140px;height:auto;" />'
        )
    else:
        logo_html = (
            '<div class="softude-logo" style="width:36px;height:36px;border-radius:10px;'
            'background:linear-gradient(135deg,#14b8a6,#0ea5e9);'
            'color:#041016;font-size:14px;font-weight:800;letter-spacing:-0.5px;line-height:36px;'
            'text-align:center;margin-bottom:12px;">AI</div>'
        )

    badge_html = ""
    if badge:
        badge_html = (
            f'<span class="softude-badge" style="display:inline-block;padding:6px 12px;'
            f'border-radius:999px;background:{badge_bg};color:{badge_text};font-size:11px;'
            f'font-weight:700;letter-spacing:0.7px;text-transform:uppercase;">'
            f"{escape(badge)}</span>"
        )

    row_html = []
    for index, (label, value) in enumerate(rows):
        border = "border-top:1px solid #f1f5f9;" if index else ""
        row_class = f"softude-row softude-row-{min(index + 1, 6)}"
        row_html.append(
            f'<tr class="{row_class}">'
            f'<td style="padding:13px 16px;{border}color:#64748b;font-size:13px;">{escape(label)}</td>'
            f'<td align="right" style="padding:13px 16px;{border}color:#0f172a;font-size:13px;'
            f'font-weight:700;word-break:break-word;">{escape(value)}</td>'
            "</tr>"
        )

    cta_html = ""
    if cta_label and cta_url:
        cta_html = (
            f'<div class="softude-cta-wrap" style="margin-top:26px;">'
            f'<a class="softude-cta" href="{escape(cta_url, quote=True)}" '
            f'style="display:inline-block;background:{accent};color:#ffffff;text-decoration:none;'
            f'padding:12px 20px;border-radius:8px;font-size:14px;font-weight:700;">'
            f"{escape(cta_label)}</a></div>"
        )

    note = footer_note or (
        f"This notification was generated by {brand_name()} — your {product_name()} operations product."
    )

    return f"""<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light" />
    <style>
      @keyframes softudeFadeUp {{
        from {{ opacity: 0; transform: translateY(14px); }}
        to {{ opacity: 1; transform: translateY(0); }}
      }}
      @keyframes softudeLogoIn {{
        from {{ opacity: 0; transform: translateY(-6px) scale(0.96); }}
        to {{ opacity: 1; transform: translateY(0) scale(1); }}
      }}
      @keyframes softudeBadgePop {{
        0% {{ opacity: 0; transform: scale(0.96); }}
        100% {{ opacity: 1; transform: scale(1); }}
      }}
      @keyframes softudeCtaPulse {{
        0%, 100% {{ transform: scale(1); }}
        50% {{ transform: scale(1.02); }}
      }}
      @keyframes softudeRowReveal {{
        from {{ opacity: 0; transform: translateX(-8px); }}
        to {{ opacity: 1; transform: translateX(0); }}
      }}
      .softude-card {{
        animation: softudeFadeUp 0.65s ease-out both;
      }}
      .softude-header {{
        background: #0b1220;
      }}
      .softude-logo {{
        animation: softudeLogoIn 0.8s ease-out both;
      }}
      .softude-title {{
        animation: softudeFadeUp 0.7s ease-out 0.12s both;
      }}
      .softude-eyebrow {{
        animation: softudeFadeUp 0.7s ease-out 0.2s both;
      }}
      .softude-badge {{
        animation: softudeBadgePop 0.55s ease-out 0.25s both;
      }}
      .softude-intro {{
        animation: softudeFadeUp 0.7s ease-out 0.32s both;
      }}
      .softude-details {{
        animation: softudeFadeUp 0.75s ease-out 0.4s both;
      }}
      .softude-cta-wrap {{
        animation: softudeFadeUp 0.75s ease-out 0.48s both;
      }}
      .softude-cta {{
        animation: softudeCtaPulse 2.6s ease-in-out infinite;
      }}
      .softude-footer {{
        animation: softudeFadeUp 0.7s ease-out 0.55s both;
      }}
      .softude-row {{
        animation: softudeRowReveal 0.55s ease-out both;
      }}
      .softude-row-1 {{ animation-delay: 0.45s; }}
      .softude-row-2 {{ animation-delay: 0.52s; }}
      .softude-row-3 {{ animation-delay: 0.59s; }}
      .softude-row-4 {{ animation-delay: 0.66s; }}
      .softude-row-5 {{ animation-delay: 0.73s; }}
      .softude-row-6 {{ animation-delay: 0.8s; }}
      @media (prefers-reduced-motion: reduce) {{
        *, *::before, *::after {{
          animation: none !important;
          transition: none !important;
        }}
      }}
    </style>
  </head>
  <body style="margin:0;background:#eef3f7;font-family:Arial,Helvetica,sans-serif;color:#17202a;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#eef3f7;padding:28px 12px;">
      <tr><td align="center">
        <table class="softude-card" role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
          <tr>
            <td class="softude-header" style="background:#0b1220;padding:24px 28px;border-bottom:3px solid {accent};">
              {logo_html}
              <div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#5eead4;font-weight:700;">{brand}</div>
              <div style="margin-top:4px;font-size:12px;color:#94a3b8;">{product} notification</div>
              <div class="softude-title" style="margin-top:12px;font-size:24px;line-height:32px;color:#ffffff;font-weight:700;">{escape(title)}</div>
              <div class="softude-eyebrow" style="margin-top:6px;font-size:13px;color:#94a3b8;">{escape(eyebrow)}</div>
            </td>
          </tr>
          <tr>
            <td style="padding:28px;">
              {badge_html}
              <div class="softude-intro" style="margin:{"18px" if badge else "0"} 0 22px;font-size:16px;line-height:26px;color:#374151;">
                {intro_html}
              </div>
              <table class="softude-details" role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #e2e8f0;border-radius:8px;">
                {"".join(row_html)}
              </table>
              {cta_html}
              <p style="margin:24px 0 0;font-size:12px;line-height:18px;color:#94a3b8;">{escape(note)}</p>
            </td>
          </tr>
          <tr>
            <td class="softude-footer" style="padding:16px 28px 22px;background:#ffffff;border-top:1px solid #e2e8f0;">
              <div style="font-size:11px;letter-spacing:0.4px;color:#94a3b8;text-align:center;">
                Powered by <strong style="color:#0f766e;">{product}</strong> · {brand}
              </div>
            </td>
          </tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>"""


def build_intake_owner_email(
    *,
    category: str,
    submitted_by: str,
    request_text: str,
    external_submission_id: str,
    submission_id: str,
    monday: dict[str, Any] | None = None,
) -> tuple[str, str, str]:
    """Return ``(subject, body_text, body_html)`` for Intake category-owner notify."""
    monday = monday or {}
    board = monday.get("board") if isinstance(monday.get("board"), dict) else {}
    monday_url = str(board.get("url") or "").strip()
    category_label = category.replace("_", " ").title()
    subject = f"[Intake] {category_label} · {external_submission_id}"

    preview = request_text.strip()
    if len(preview) > 280:
        preview = preview[:277].rstrip() + "..."

    console = dashboard_url()
    detail_url = f"{console}/intake-agent/{submission_id}"
    cta_url = monday_url or detail_url
    cta_label = "Open in Monday" if monday_url else "Review in Ops Console"

    body_text = (
        f"New Intake assignment — {category_label}\n\n"
        f"A client intake was routed to your category by Softude AI.\n\n"
        f"Category: {category_label}\n"
        f"Submitted by: {submitted_by}\n"
        f"Submission ID: {external_submission_id}\n"
        f"Request:\n{request_text}\n\n"
        f"Open: {cta_url}\n\n"
        f"This notification was generated by Softude Ops Console."
    )

    intro_html = (
        "A client intake was classified and assigned to your category by "
        f"<strong>{escape(product_name())}</strong>."
    )
    body_html = render_branded_email(
        eyebrow="Intake Agent",
        title=f"{category_label} assigned",
        intro_html=intro_html,
        badge=category_label,
        rows=[
            ("Category", category_label),
            ("Submitted by", submitted_by),
            ("Submission ID", external_submission_id),
            ("Request", preview),
        ],
        cta_label=cta_label,
        cta_url=cta_url,
        footer_note=(
            "You received this because you are the configured owner for this "
            "Intake category in Softude Ops Console."
        ),
    )
    return subject, body_text, body_html


def build_vendor_owner_email(
    *,
    status: str,
    vendor_name: str,
    project_id: str,
    hours_pending: str | float | int,
    dashboard_url_override: str | None = None,
) -> tuple[str, str, str]:
    """Return ``(subject, body_text, body_html)`` for vendor follow-up owner notify."""
    is_escalate = status == "ESCALATE"
    accent = "#ef4444" if is_escalate else "#f59e0b"
    badge_bg = "#fee2e2" if is_escalate else "#fef3c7"
    badge_text = "#b91c1c" if is_escalate else "#b45309"
    action_label = "Escalation" if is_escalate else "Reminder"
    review_url = (dashboard_url_override or f"{dashboard_url()}/vendor-agent").strip()
    hours = str(hours_pending)

    subject = f"Vendor {action_label}: {vendor_name} · {project_id}"
    body_text = (
        f"Vendor {action_label}\n\n"
        f"An approved vendor follow-up action needs your attention.\n\n"
        f"Vendor: {vendor_name}\n"
        f"Project ID: {project_id}\n"
        f"Hours pending: {hours}\n"
        f"Action: {status.replace('_', ' ').title()}\n\n"
        f"Review: {review_url}\n\n"
        "This notification was generated by Softude Ops Console."
    )
    intro_html = (
        f"Vendor <strong>{escape(vendor_name)}</strong> on project "
        f"<strong>{escape(project_id)}</strong> has been pending for "
        f"<strong>{escape(hours)} hours</strong>."
    )
    body_html = render_branded_email(
        eyebrow="Vendor Agent",
        title=f"Vendor {action_label}",
        intro_html=intro_html,
        badge=status.replace("_", " "),
        accent=accent,
        badge_bg=badge_bg,
        badge_text=badge_text,
        rows=[
            ("Vendor", vendor_name),
            ("Project ID", project_id),
            ("Hours pending", f"{hours} h"),
            ("Recommended action", status.replace("_", " ").title()),
        ],
        cta_label="Review in Ops Console",
        cta_url=review_url,
        footer_note=(
            "This notification was generated after approval in Softude Ops Console."
        ),
    )
    return subject, body_text, body_html


def build_artwork_mismatch_email(
    *,
    project_id: str,
    status: str = "MISMATCH",
    artwork_width: str | float | None = None,
    artwork_height: str | float | None = None,
    spec_width: str | float | None = None,
    spec_height: str | float | None = None,
    dashboard_url_override: str | None = None,
) -> tuple[str, str, str]:
    """Return ``(subject, body_text, body_html)`` for artwork mismatch notify."""
    review_url = (dashboard_url_override or f"{dashboard_url()}/artwork-agent").strip()
    status_label = status.replace("_", " ").title()
    subject = f"Artwork review needed: {project_id}"

    dim_rows: list[tuple[str, str]] = [("Project ID", project_id), ("Status", status_label)]
    if artwork_width is not None and artwork_height is not None:
        dim_rows.append(("Artwork size", f"{artwork_width} × {artwork_height} in"))
    if spec_width is not None and spec_height is not None:
        dim_rows.append(("Spec size", f"{spec_width} × {spec_height} in"))

    body_text = (
        f"Artwork {status_label}\n\n"
        f"Dimensions need review for project {project_id}.\n\n"
        + "\n".join(f"{label}: {value}" for label, value in dim_rows[1:])
        + f"\n\nReview: {review_url}\n\n"
        "This notification was generated by Softude Ops Console."
    )
    intro_html = (
        f"Artwork verification flagged a <strong>{escape(status_label.lower())}</strong> "
        f"for project <strong>{escape(project_id)}</strong>. "
        "Please review the submission in the dashboard."
    )
    body_html = render_branded_email(
        eyebrow="Artwork Agent",
        title="Artwork review needed",
        intro_html=intro_html,
        badge=status_label,
        accent="#ef4444",
        badge_bg="#fee2e2",
        badge_text="#b91c1c",
        rows=dim_rows,
        cta_label="Open Artwork Agent",
        cta_url=review_url,
        footer_note=(
            "This notification was generated after approval in Softude Ops Console."
        ),
    )
    return subject, body_text, body_html


def build_email_overdue_notify(
    *,
    thread_id: str,
    hours_pending: str | float | int,
    status: str = "UNANSWERED",
    priority: str = "normal",
    draft_reply: str = "",
    dashboard_url_override: str | None = None,
) -> tuple[str, str, str]:
    """Return ``(subject, body_text, body_html)`` for a single overdue email thread."""
    review_url = (dashboard_url_override or f"{dashboard_url()}/email-agent").strip()
    hours = str(hours_pending)
    is_critical = status == "CRITICAL"
    badge = "Critical" if is_critical else "Unanswered"
    accent = "#ef4444" if is_critical else "#6366f1"
    badge_bg = "#fee2e2" if is_critical else "#e0e7ff"
    badge_text = "#b91c1c" if is_critical else "#4338ca"
    title = "Client email critical" if is_critical else "Client email overdue"
    subject = f"Client email {badge.lower()} · thread {thread_id}"

    draft_block = ""
    if draft_reply.strip():
        draft_block = f"\nSuggested reply:\n{draft_reply.strip()}\n"

    body_text = (
        f"Client email needs attention ({badge})\n\n"
        f"A client email thread has exceeded the response threshold.\n\n"
        f"Thread ID: {thread_id}\n"
        f"Hours pending: {hours}\n"
        f"Status: {status}\n"
        f"Priority: {priority}\n"
        f"{draft_block}\n"
        f"Review: {review_url}\n\n"
        "This notification was generated by Softude Ops Console."
    )
    intro_html = (
        "A client email thread has been <strong>unanswered</strong> for "
        f"<strong>{escape(hours)} hours</strong> and needs a response"
        + (" (critical SLA breach)." if is_critical else ".")
    )
    rows = [
        ("Thread ID", thread_id),
        ("Hours pending", f"{hours} h"),
        ("Status", status),
        ("Priority", priority),
    ]
    body_html = render_branded_email(
        eyebrow="Email Agent",
        title=title,
        intro_html=intro_html,
        badge=badge,
        accent=accent,
        badge_bg=badge_bg,
        badge_text=badge_text,
        rows=rows,
        cta_label="Open Email Agent",
        cta_url=review_url,
        footer_note=(
            "This notification was generated after approval in Softude Ops Console."
        ),
    )
    return subject, body_text, body_html


def build_email_unanswered_digest(
    *,
    threads: list[dict[str, Any]],
    dashboard_url_override: str | None = None,
) -> tuple[str, str, str]:
    """Return ``(subject, body_text, body_html)`` for unanswered thread digest."""
    count = len(threads)
    review_url = (dashboard_url_override or f"{dashboard_url()}/email-agent").strip()
    subject = f"{count} unanswered client email thread(s)"

    lines = [f"There are {count} unanswered client email thread(s).", ""]
    preview_rows: list[tuple[str, str]] = []
    for row in threads[:8]:
        thread_id = str(row.get("thread_id") or "—")
        hours = str(row.get("hours_pending") or "—")
        snippet = str(row.get("last_message_text") or "")[:80].strip() or "—"
        lines.append(f"- {thread_id}: {hours}h — {snippet}")
        preview_rows.append((thread_id, f"{hours}h · {snippet}"))
    if count > 8:
        preview_rows.append(("More threads", f"+{count - 8} additional"))

    body_text = "\n".join(lines) + f"\n\nReview: {review_url}\n"
    intro_html = (
        f"<strong>{count}</strong> client email thread(s) are waiting for a team response."
    )
    body_html = render_branded_email(
        eyebrow="Email Agent",
        title="Unanswered threads digest",
        intro_html=intro_html,
        badge=f"{count} threads",
        accent="#6366f1",
        badge_bg="#e0e7ff",
        badge_text="#4338ca",
        rows=preview_rows or [("Threads", "0")],
        cta_label="Open Email Agent",
        cta_url=review_url,
    )
    return subject, body_text, body_html


def build_client_ack_email(
    *,
    body_text: str,
    subject: str | None = None,
) -> tuple[str, str]:
    """Return ``(body_text, body_html)`` for client auto-ack (client-facing)."""
    message = body_text.strip()
    title = "We received your message"
    intro_html = (
        "Thank you for reaching out. Our team has received your email and "
        "will get back to you shortly."
    )
    body_html = render_branded_email(
        eyebrow="Client Services",
        title=title,
        intro_html=intro_html,
        rows=[("Your message", message[:280] + ("..." if len(message) > 280 else ""))],
        accent="#14b8a6",
        footer_note=(
            f"This is an automated acknowledgment from {brand_name()}. "
            "A team member will follow up personally."
        ),
    )
    return message, body_html


def build_followup_owner_email(
    *,
    status: str,
    project_id: str,
    project_name: str,
    stage: str,
    days_inactive: str,
    dashboard_url_override: str | None = None,
) -> tuple[str, str, str]:
    """Return ``(subject, body_text, body_html)`` for follow-up owner notify."""
    label = "ESCALATION" if status == "ESCALATE" else "FOLLOW-UP"
    accent = "#ef4444" if status == "ESCALATE" else "#14b8a6"
    badge_bg = "#fee2e2" if status == "ESCALATE" else "#ccfbf1"
    badge_text = "#b91c1c" if status == "ESCALATE" else "#0f766e"
    review_url = (dashboard_url_override or dashboard_url(
        "https://ai-automation-agents-plum.vercel.app/audit-log"
    )).strip()

    subject = f"Action required: {project_name} · {project_id}"
    body_text = (
        f"Project {label.title()}\n\n"
        f"{project_name} ({project_id}) has had no recorded activity for "
        f"{days_inactive} days and needs attention.\n\n"
        f"Project: {project_name}\n"
        f"Project ID: {project_id}\n"
        f"Stage: {stage}\n"
        f"Days inactive: {days_inactive}\n"
        f"Recommended action: {status.replace('_', ' ').title()}\n\n"
        f"Review project: {review_url}\n\n"
        "This notification was generated by Softude Ops Console."
    )
    intro_html = (
        f"<strong>{escape(project_name)}</strong> has had no recorded activity for "
        f"<strong>{escape(days_inactive)} days</strong> and needs your attention."
    )
    body_html = render_branded_email(
        eyebrow="Follow-up Agent",
        title=f"Project {label.title()}",
        intro_html=intro_html,
        badge=status.replace("_", " "),
        accent=accent,
        badge_bg=badge_bg,
        badge_text=badge_text,
        rows=[
            ("Project", project_name),
            ("Project ID", project_id),
            ("Stage", stage),
            ("Inactive", f"{days_inactive} days"),
        ],
        cta_label="Review in Ops Console",
        cta_url=review_url,
        footer_note=(
            "This notification was generated after approval in Softude Ops Console."
        ),
    )
    return subject, body_text, body_html


def build_installer_owner_email(
    *,
    project_id: str,
    project_name: str,
    install_region: str,
    installer_name: str,
    installer_email: str,
    installer_region: str,
    match_type: str,
    dashboard_url_override: str | None = None,
) -> tuple[str, str, str]:
    """Return ``(subject, body_text, body_html)`` with draft installer outreach."""
    review_url = (dashboard_url_override or dashboard_url(
        "https://ai-automation-agents-plum.vercel.app/audit-log"
    )).strip()
    outreach_to = installer_email or "(add installer email on Monday roster)"
    match_label = match_type.replace("_", " ").title() if match_type else "Match"

    subject = f"Installer match approved: {project_name} · {project_id}"
    body_text = (
        f"Installer match approved\n\n"
        f"Project: {project_name}\n"
        f"Project ID: {project_id}\n"
        f"Install region: {install_region}\n"
        f"Recommended installer: {installer_name}\n"
        f"Installer region: {installer_region}\n"
        f"Match type: {match_label}\n\n"
        f"Draft outreach to: {outreach_to}\n"
        "Suggested message:\n"
        f"Hi {installer_name.split()[0] if installer_name else 'team'},\n"
        f"We have an install opportunity for {project_name} in {install_region}. "
        "Please confirm availability and we will share site details.\n\n"
        f"Review in Ops Console: {review_url}\n\n"
        "This notification was generated by Softude Ops Console."
    )
    intro_html = (
        f"Approved match for <strong>{escape(project_name)}</strong> in "
        f"<strong>{escape(install_region)}</strong>."
    )
    body_html = render_branded_email(
        eyebrow="Installer Matching",
        title="Draft installer outreach",
        intro_html=intro_html,
        badge=match_label,
        accent="#6366f1",
        badge_bg="#e0e7ff",
        badge_text="#4338ca",
        rows=[
            ("Project", project_name),
            ("Project ID", project_id),
            ("Installer", installer_name),
            ("Installer email", outreach_to),
            ("Installer region", installer_region or "—"),
        ],
        cta_label="Review in Ops Console",
        cta_url=review_url,
        footer_note=(
            "Send the draft outreach manually or forward this email to the installer."
        ),
    )
    return subject, body_text, body_html


def build_phase3_owner_email(
    *,
    agent_label: str,
    project_id: str,
    status: str,
    headline: str,
    summary: str,
    rows: list[tuple[str, str]],
    dashboard_url_override: str | None = None,
) -> tuple[str, str, str]:
    """Branded owner notification for Phase 3 vision agents."""
    review_url = (dashboard_url_override or dashboard_url(
        "https://ai-automation-agents-plum.vercel.app/audit-log"
    )).strip()
    subject = f"{agent_label}: {headline} · {project_id}"
    body_text = (
        f"{headline}\n\n"
        f"Project ID: {project_id}\n"
        f"Status: {status}\n\n"
        f"{summary}\n\n"
        f"Review in Ops Console: {review_url}\n\n"
        "This notification was generated after approval in Softude Ops Console."
    )
    intro_html = (
        f"<strong>{escape(headline)}</strong> for project "
        f"<strong>{escape(project_id)}</strong>."
    )
    if summary.strip():
        intro_html += f"<br /><br />{escape(summary[:500])}"
    body_html = render_branded_email(
        eyebrow=agent_label,
        title=headline,
        intro_html=intro_html,
        badge=status.replace("_", " "),
        accent="#8b5cf6",
        badge_bg="#ede9fe",
        badge_text="#5b21b6",
        rows=rows,
        cta_label="Review in Ops Console",
        cta_url=review_url,
        footer_note="Generated after human approval in Softude Ops Console.",
    )
    return subject, body_text, body_html
